# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/python:2.7.13

version: 2
jobs:
  build-staging:
    <<: *defaults

    steps:
      - checkout

      - run:
          name: install
          command: |
            bash install.sh
      - run:
          name: build
          command: |
            bash build.sh
      - run:
          name: deploy staging docs
          command: |
            aws s3 sync ./ s3://staging-docs.bluz.io --delete --region us-east-1

  build-prod:
    <<: *defaults

    steps:
      - checkout

      - run:
          name: install
          command: |
            bash install.sh
      - run:
          name: build
          command: |
            bash build.sh
      - run:
          name: deploy staging docs
          command: |
            aws s3 sync ./ s3://docs.bluz.io --delete --region us-east-1

workflows:
  version: 2
  build-workflow:
    jobs:
      - build-staging:
          filters:
            branches:
              only: master
      - approve-prod:
          type: approval
          requires:
            - build-staging
          filters:
            branches:
              only: master
      - build-prod:
          requires:
            - approve-prod
            - build-staging
          filters:
            branches:
              only: master